---
title: "Baby names in the United States"
params:
  sex: M
  year: 2016
output:
  html_document:
    df_print: paged
---

Baby names in the United States
--------------------------------

```{r include=FALSE}
library(babynames)
library(tidyverse)
# Get the 10 most popular names in the given year for the given gender
top10 <- babynames %>%
           filter(sex==params$sex, year==params$year) %>%
           group_by(name) %>%
           summarize(total = sum(n)) %>%
           arrange(desc(total)) %>%
           slice(1:10)

if(params$sex=="M") {
    boysorgirls <- "boys"
} else {
    boysorgirls <- "girls"
}
```


Top 10 baby names for `r boysorgirls` in `r params$year`
---------------------------------------------------------


```{r echo=FALSE}
library(knitr)
top10 %>%
    kable()
```


History
-------


```{r echo=FALSE}
# extract popularity of those names over the last 50 years
chartdata <- babynames %>%
                  filter(year>params$year-50, year<=params$year,
                         sex==params$sex,
                         name %in% top10$name) %>%
                  group_by(name, year) %>%
                  summarize(total = sum(n))

# Prevent ggplot from showing the names in alphabetical order
chartdata <- chartdata %>%
                 ungroup() %>%
                 mutate(name=factor(name, levels=top10$name))

# Generate time series plots
ggplot(data=chartdata) +
    geom_line(aes(x=year, y=total)) +
    facet_wrap(~name)
```